Merged branch "medipacksupport" from "git" into "svn"
The following commits were merged:

commit 0d1b5eec2cca8afdeea3cdffa196efb6cfd60a53
Merge: 72d114b 33bfdb5
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Nov 5 10:03:04 2018 +0000

    Merge branch 'medipackSupport' into 'medipacksupport'

    Medipack support

    See merge request adol-c/adol-c!26

commit 33bfdb5a006c782489bfef1b651ca3bdbceefaf2
Merge: ac55eab cf82982
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:19:31 2018 +0100

    Merge branch 'medipackSupport' into temp

commit ac55eab9dd8cb8c84926ee56456076392a047c1a
Merge: 72d114b caaac60
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:14:09 2018 +0100

    Merge remote-tracking branch 'origin/master' into temp

commit cf82982421aaa7d83405ffa3d0c9b6ef88251d0c
Merge: 6aeca20 caaac60
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 30 11:13:25 2018 +0100

    Merge remote-tracking branch 'origin/master' into medipackSupport

commit 6aeca205c2448b4bbc915eb76153ebde19448573
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Tue Oct 23 22:30:28 2018 +0200

    Added suport for ZOS, FOS, FOV forward and reverse.

commit caaac60da4c61b370d106c68064d38c42a7cb6e3
Merge: cc2e0b3 70fc288
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Oct 8 08:53:40 2018 +0000

    Merge branch 'fix_adtl_hov_refcntr' into 'master'

    Fix undefined reference to adtl_hov::refcounter::refcnt

    See merge request adol-c/adol-c!24

commit 70fc288b9ab95b16d3179fcf239ee2208ae1a2c4
Author: Jean-Paul Pelteret <jppelteret@gmail.com>
Date:   Mon Oct 1 20:53:03 2018 +0200

    Fix undefined reference to adtl_hov::refcounter::refcnt

commit cc2e0b3154fb6e62580def4501c4cf3f3d8e32ef
Merge: d7400f5 7c7f24b
Author: Kshitij Kulshreshtha <kshitij@math.upb.de>
Date:   Mon Oct 1 12:26:39 2018 +0000

    Merge branch 'docu' into 'master'

    Refactor tapeless to traceless

    See merge request adol-c/adol-c!23

commit ca397962cde23bde80e03924893e09c84d8728bf
Merge: 9cbc432 d7400f5
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Fri Sep 28 10:07:41 2018 +0200

    Merge remote-tracking branch 'origin/master' into medipackSupport

commit 9cbc4324e0d3e19f97ba5c5474121f0189e60f83
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Sep 27 14:38:30 2018 +0200

    Missing MeDiPack initialization on trace_on.

commit 76c30290365830d2370a354af949f3bf42df3885
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Sep 27 09:55:42 2018 +0200

    Null pointer fix for initialization.

commit 7c7f24b25479870d58ff19d78a6e394ca28ddb58
Author: mflehmig <martin.schroschk@tu-dresden.de>
Date:   Thu Sep 20 13:16:06 2018 +0200

    Refactor tapeless to traceless

    As far as I can see, the official wording is traceless forward mode.
    Additonally, the latex label and refs changed to 'traceless'.

commit 72d114b7ac42b8ac493030cedd1df8c9746ba5d4
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Oct 19 09:25:19 2017 +0200

    Added support for MeDiPack library.

    Enable it with the configure options:
    --enable-medipack --with-medipack=<path to MeDiPack>

    Tutorial on a how to use will follow.

commit b4ca76279d28407f29901d40953d02a0c5c9140e
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Mon May 7 14:45:13 2018 +0200

    Added support for cbrt function.

commit bc7b8ca61865058fac097410fd94a44fba281131
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Mar 1 10:31:18 2018 +0100

    Changes for new interface.

commit cd1e82778c8540221b24559d5097bf6d00597e19
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Nov 16 14:31:07 2017 +0100

    Changes to new MeDiPack interface for adjoint values.

commit 55bcb0ffd5a9496817bffac0bd2c9489ed8ce992
Author: Max Sagebaum <max.sagebaum@scicomp.uni-kl.de>
Date:   Thu Oct 19 09:25:19 2017 +0200

    Added support for MeDiPack library.

    Enable it with the configure options:
    --enable-medipack --with-medipack=<path to MeDiPack>

    Tutorial on a how to use will follow.

git-svn-id: https://projects.coin-or.org/svn/ADOL-C/trunk@762 94ac48a7-3327-4b6a-8511-9a4036a20e83